name: Validate Workflow on PR

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/**'

jobs:
  validate-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate workflow YAML files
        run: |
          set -e
          find .github/workflows -name '*.yml' -print0 | xargs -0 yamllint -c .yamllint.yml

      - name: Validate workflow schema
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          script: |
            set -e
            const Ajv = require('ajv');
            const axios = require('axios');
            const yaml = require('js-yaml');
            const fs = require('fs').promises;
  
            const schema = await axios.get(
              'https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json'
            );
  
            const files = await fs.readdir('.github/workflows');
            const ymlFiles = files.filter(file => file.endsWith('.yml'));
  
            for (const file of ymlFiles) {
              const content = await fs.readFile(`.github/workflows/${file}`, 'utf8');
              const target = yaml.load(content);
  
              const ajv = new Ajv({ strict: false, allErrors: true });
              const validator = ajv.compile(schema.data);
              const valid = validator(target);
              if (!valid) {
                console.error(`Validation failed with the following errors:`);
                console.error(validator.errors);
                process.exit(1);
              } else {
                console.log(`Workflow is valid`);
              }
  