name: Welcome New Contributor
on:
  pull_request:
    types: [opened]
    paths: 
      - 'TSC_MEMBERS.json'
jobs:
  welcome:
    # if: github.event.pull_request.merged 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout main branch 
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Save file from main branch 
        run: cp TSC_MEMBERS.json $HOME
      - name: Checkout other branch
        uses: actions/checkout@v2
        with: 
          ref: ${{github.event.inputs.branch}}
      - name: Compare files
        run: diff $HOME/TSC_MEMBERS.json TSC_MEMBERS.json
      - name: Display welcome message
        if: ${{ ! diff -q $HOME/TSC_MEMBERS.json  TSC_MEMBERS.json  >/dev/null; }}
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            const welcomeMessage = `Welcome to AsyncAPI. Thanks a lot for creating your first pull request. Please check out our [contributors guide](https://github.com/asyncapi/community/blob/master/CONTRIBUTING.md) useful for opening a pull request.<br />Keep in mind there are also other channels you can use to interact with AsyncAPI community.`;
            const { owner, repo } = context.repo;
            const { number: issue_number } = context.issue;
            return github.issues.createComment({ owner, repo, issue_number, body: welcomeMessage });