# # A github action to check the reaction on pr and issues . 

name: Check Reactions on Pr and Issue
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, closed]
jobs:
  check-reactions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add label to issues with more than 5 reactions
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.test_token }}
          script: |
            const { owner, repo } = context.repo;
            // Check issues with more than 5 reactions
            const issues = await github.paginate(github.rest.issues.listForRepo.endpoint({
              owner,
              repo,
              state: 'open',
            }));

            for (const issue of issues) {
              console.log(`Checking issue #${issue.number}`);
              if (issue.reactions && issue.reactions.total_count > 5) {
                console.log(`Issue #${issue.number} has ${issue.reactions.total_count} reactions`);
                await github.rest.issues.addLabels({
                  owner,
                  repo,
                  issue_number: issue.number,
                  labels: ['more than 5 reactions'],
                });
              }
            }
            // Check pull requests with more than 5 reactions
            const pulls = await github.paginate(github.rest.pulls.list.endpoint({
              owner,
              repo,
              state: 'open',
            }));

            for (const pull of pulls) {
              console.log(`Checking pull request #${pull.number}`);
              if (pull.reactions && pull.reactions.total_count > 5) {
                console.log(`Pull request #${pull.number} has ${pull.reactions.total_count} reactions`);
                await github.rest.issues.addLabels({
                  owner,
                  repo,
                  issue_number: pull.number,
                  labels: ['more than 5 reactions'],
                });
              }
            }
            