# # A github action to check the reaction on pr and issues . 

# name: Check Reactions on Pr and Issue
# on:
#   issues:
#     types: [opened]
#   pull_request:
#     types: [opened, closed]
# jobs:
#   check-reactions:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Check Reactions
#         env:
#           GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
#         run: |
#           echo "Checking reactions..."
#             issues=$(curl -H "Authorization: token $GITHUB_TOKEN" \
#             "https://api.github.com/repos/${{ github.repository }}/issues?state=all" \
#             | jq '.[] | select(.reactions.total_count > 5) | .number')
#           echo "Found issues with more than 5 reactions: $issues"
#           for issue in $issues; do
#             echo "Adding label to issue #$issue..."
#             curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
#               -H "Accept: application/vnd.github.v3+json" \
#               "https://api.github.com/repos/${{ github.repository }}/issues/$issue/labels" \
#               -d '{"labels": ["more than 5 reactions"]}'
#           done
#           echo "Checking reactions..."
#           prs=$(curl -H "Authorization: token $GITHUB_TOKEN" \
#           "https://api.github.com/repos/${{ github.repository }}/pulls?state=all" \
#           | jq '.[] | select(.reactions.total_count > 5) | .number')
#           echo "Found pr with more than 5 reactions: $prs"
#           if [ -z "$prs" ]; then
#             echo "No pull requests with more than 5 reactions found."
#           else
#             for pr in $prs; do
#               echo "Adding label to pr #$pr..."
#               curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
#               -H "Accept: application/vnd.github.v3+json" \
#               "https://api.github.com/repos/${{ github.repository }}/pulls/$pr/labels" \
#               -d '{"labels": ["more than 5 reactions"]}'
#             done
#           fi



        

name: Check Reactions on Pr and Issue
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, closed]
jobs:
  check-reactions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add label to issues and pull requests with more than 5 reactions
        uses: actions/github-script@v4
        with:
           script: |
            const { owner, repo } = context.repo;
            // Get all labels for the repository
            const labelsResponse = await github.issues.listLabelsForRepo({
              owner,
              repo,
            });

            if (labelsResponse.data) {
              console.log(`Found ${labelsResponse.data.length} labels`);
              const moreThan5ReactionsLabel = labelsResponse.data.find((label) => label.name === 'more than 5 reactions');
              if (moreThan5ReactionsLabel) {
                const moreThan5ReactionsLabelId = moreThan5ReactionsLabel.id;

                // Check issues with more than 5 reactions and without the label
                const issuesResponse = await github.issues.listForRepo({
                  owner,
                  repo,
                  state: 'all',
                });
                if (issuesResponse.data) {
                  console.log(`Found ${issuesResponse.data.length} issues`);
                  const issuesWithoutLabelResponse = await github.issues.listForRepo({
                    owner,
                    repo,
                    state: 'all',
                    labels: moreThan5ReactionsLabelId,
                    per_page: 100,
                  });
                  const issuesWithoutLabel = issuesWithoutLabelResponse.data;
                  console.log(`Found ${issuesWithoutLabel.length} issues without the label`);
                  for (const issue of issuesWithoutLabel) {
                    console.log(`Checking issue #${issue.number}`);
                    if (issue.reactions && issue.reactions.total_count > 5) {
                      console.log(`Issue #${issue.number} has ${issue.reactions.total_count} reactions`);
                      await github.issues.addLabels({
                         owner,
                         repo,
                         issue_number: issue.number,
                         labels: [moreThan5ReactionsLabel],
                      });
                    }
                  }
                }

                // Check pull requests with more than 5 reactions and without the label
                const pullsResponse = await github.pulls.list({
                  owner,
                  repo,
                  state: 'all',
                });
                if (pullsResponse.data) {
                  console.log(`Found ${pullsResponse.data.length} pull requests`);
                  const pullsWithoutLabelResponse = await github.pulls.list({
                    owner,
                    repo,
                    state: 'all',
                    labels: moreThan5ReactionsLabelId,
                    per_page: 100,
                  });
                  const pullsWithoutLabel = pullsWithoutLabelResponse.data;
                  console.log(`Found ${pullsWithoutLabel.length} pull requests without the label`);
                  for (const pull of pullsWithoutLabel) {
                    console.log(`Checking pull request #${pull.number}`);
                    if (pull.reactions && pull.reactions.total_count > 5) {
                      console.log(`Pull request #${pull.number} has ${pull.reactions.total_count} reactions`);
                      await github.issues.addLabels({
                        owner,
                        repo,
                        issue_number: pull.number,
                        labels: [moreThan5ReactionsLabel],
                      });
                    }
                  }
                }
              }
            }