# A github action to check the reaction on pr and issues . 

name: Check Reactions on Pr and Issue
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, closed]
jobs:
  check-reactions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check Reactions
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
        run: |
          echo "Checking reactions..."
          issues=$(curl -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=all" \
            | jq '.[] | select(.reactions.total_count > 5) | .number')
          echo "Found issues with more than 5 reactions: $issues"
          for issue in $issues; do
            echo "Adding label to issue #$issue..."
            curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/issues/$issue/labels" \
              -d '{"labels": ["more than 5 reactions"]}'
          done
          echo "Checking reactions..."
          prs=$(curl -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=all" \
            | jq '.[] | select(.reactions.total_count > 5) | .number')
          echo "Found pr with more than 5 reactions: $prs"
          for pr in $prs; do
            echo "Adding label to pr #$pr..."
            curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/$pr/labels" \
              -d '{"labels": ["more than 5 reactions"]}'
          done




