name: Welcome New Contributor
on:
  pull_request:
    types: [opened]
    paths: 
      - 'TSC_MEMBERS.json'
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch 
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          # path: testRepo-main
      # - name: Save file from main branch 
      #   run: cp TSC_MEMBERS.json $HOME
      - name: Checkout other branch
        uses: actions/checkout@v3
      - name: Print working directory
        run: |
          pwd
          ls -la
      - name: List directory
        run: ls testRepo
      - name: Compare files
        id: compare-files
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require("fs");
            const main_file = JSON.parse(fs.readFileSync(`testRepo/TSC_MEMBERS.json`));
            const new_file = JSON.parse(fs.readFileSync('TSC_MEMBERS.json'));
            const added = new_file.filter(
              (newObj) => !main_file.some((oldObj) => oldObj.github === newObj.github)
            );
            const removed = main_file.filter(
              (oldObj) => !new_file.some((newObj) => newObj.github === oldObj.github)
            );
            if(added.length > 0) {
              core.info(`Added Contributers : ${JSON.stringify(added)}`)
              core.setOutput("added_contributors", added.map((obj) => obj.github).join(","));
            }
            if(removed.length > 0) {
              core.setOutput("removed", "true");
              core.info(`Removed Contributers : ${removed}`)
            }               
      - name: Display welcome message
        if: steps.compare-files.outputs.added_contributors != ''
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            const newContributors = `${{steps.compare-files.outputs.added_contributors}}`.split(",");
            const welcomeMessage = newContributors.map((contributor) => `@${contributor.trim().replace(/^@/, '')} I have invited you to join the AsyncAPI organization and you will soon be added to the team that lists all TSC members.
            
            We use this team to mention in different discussions in different places in GitHub where TSC opinion is needed or even voting on some topic. Once TSC is mentioned:
            
            - You get GitHub notification
            - We also drop notification in our slack in #95_bot-tsc-members-mentioned channel
            - We drop an email to people that subscribed to TSC news here https://www.asyncapi.com/community/tsc
            
            Pick the channel for notifications that you prefer. Welcome aboard! We are excited to have you as part of the team.`).join("\n");
            
            const { owner, repo } = context.repo;
            const { number: issue_number } = context.issue;
            return github.rest.issues.createComment({ owner, repo, issue_number, body: welcomeMessage });



