name: YAML Lint Check

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/**'

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install YAML Lint
        run: npm install yaml-lint

      - name: Lint YAML Files
        run: |
          set -e
          find .github/workflows -type f -name "*.yml" -print0 | xargs -0 ./node_modules/.bin/yamllint -q

      - name: List YAML files to validate
        run: |
          set -e
          files=$(find .github/workflows -name '*.yml')
          echo "Validating the following files:"
          echo "$files"
      - name: Validate workflow schema
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
        run: node ./scripts/yaml-valid.js