# # A github action to check the reaction on pr and issues . 

# name: Check Reactions on Pr and Issue
# on:
#   issues:
#     types: [opened]
#   pull_request:
#     types: [opened, closed]
# jobs:
#   check-reactions:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Check Reactions
#         env:
#           GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
#         run: |
#           echo "Checking reactions..."
#             issues=$(curl -H "Authorization: token $GITHUB_TOKEN" \
#             "https://api.github.com/repos/${{ github.repository }}/issues?state=all" \
#             | jq '.[] | select(.reactions.total_count > 5) | .number')
#           echo "Found issues with more than 5 reactions: $issues"
#           for issue in $issues; do
#             echo "Adding label to issue #$issue..."
#             curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
#               -H "Accept: application/vnd.github.v3+json" \
#               "https://api.github.com/repos/${{ github.repository }}/issues/$issue/labels" \
#               -d '{"labels": ["more than 5 reactions"]}'
#           done
#           echo "Checking reactions..."
#           prs=$(curl -H "Authorization: token $GITHUB_TOKEN" \
#           "https://api.github.com/repos/${{ github.repository }}/pulls?state=all" \
#           | jq '.[] | select(.reactions.total_count > 5) | .number')
#           echo "Found pr with more than 5 reactions: $prs"
#           if [ -z "$prs" ]; then
#             echo "No pull requests with more than 5 reactions found."
#           else
#             for pr in $prs; do
#               echo "Adding label to pr #$pr..."
#               curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
#               -H "Accept: application/vnd.github.v3+json" \
#               "https://api.github.com/repos/${{ github.repository }}/pulls/$pr/labels" \
#               -d '{"labels": ["more than 5 reactions"]}'
#             done
#           fi



        

name: Check Reactions on Pr and Issue
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, closed]
jobs:
  check-reactions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add label to issues with more than 5 reactions
        uses: actions/github-script@v4
        with:
          script: |
            const { owner, repo } = context.repo;
            const { data: issues } = await github.issues.listForRepo({
              owner,
              repo,
              state: 'open'
            });

            console.log(`Found ${issues.length} issues`);

            const issuesWithoutLabel = issues.filter(issue => !issue.labels.some(label => label.name === 'more than 5 reactions'));

            console.log(`Found ${issuesWithoutLabel.length} issues without label`);

            for (const issue of issuesWithoutLabel) {
              console.log(`Checking issue #${issue.number}`);
              if (issue.reactions && issue.reactions.total_count > 5) {
                console.log(`Issue #${issue.number} has ${issue.reactions.total_count} reactions`);
                await github.issues.addLabels({
                  owner,
                  repo,
                  issue_number: issue.number,
                  labels: ['more than 5 reactions'],
                });
              }
            }
      - name: Add label to pull requests with more than 5 reactions
        uses: actions/github-script@v4
        with:
          script: |
            const { owner, repo } = context.repo;
            const { data: pulls } = await github.pulls.list({
              owner,
              repo,
              state: 'open',
              sort: 'created',
              direction: 'desc'
            });

            console.log(`Found ${pulls.length} pull requests`);

            const pullsWithoutLabel = pulls.filter(pull => !pull.labels.some(label => label.name === 'more than 5 reactions'));

            console.log(`Found ${pullsWithoutLabel.length} pull requests without label`);

            for (const pull of pullsWithoutLabel) {
              console.log(`Checking pull request #${pull.number}`);
              if (pull.reactions && pull.reactions.total_count > 5) {
                console.log(`Pull request #${pull.number} has ${pull.reactions.total_count} reactions`);
                await github.issues.addLabels({
                  owner,
                  repo,
                  issue_number: pull.number,
                  labels: ['more than 5 reactions'],
                });
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
              
            