name: Welcome New Contributor
on:
  pull_request:
    types: [opened]
    paths: 
      - 'TSC_MEMBERS.json'
jobs:
  welcome:
    if: ${{ !contains(fromJson('["asyncapi-bot", "dependabot[bot]", "dependabot-preview[bot]", "allcontributors"]'), github.actor) }}
    # if: github.event.pull_request.merged 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Checkout reference repo
        uses: actions/checkout@v3
        with:
          repository: 14Richa/parentRepo1
          path: parentRepo1
      - name: Compare files
        id: compare-files
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require("fs");
            const origMembers = JSON.parse(fs.readFileSync("parentRepo1/config/TSC_MEMBER.json"));
            const newMembers = JSON.parse(fs.readFileSync("TSC_MEMBERS.json"));  
            const added = newMembers.filter(
              (newObj) => !origMembers.some((oldObj) => oldObj.name === newObj.name)
            );
            const removed = origMembers.filter(
              (oldObj) => !newMembers.some((newObj) => newObj.name === oldObj.name)
            );
            if(added.length > 0)  console.log(`::set-output name=added::true`);
            if(removed.length > 0) console.log(`::set-output name=removed::true`);
            console.log("Added members:", added);
            console.log("Removed members:", removed);
      - name: Display welcome message
        if: ${{ steps.compare-files.outputs.added == 'true' }}
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.TEST_TOKEN }}
          script: |
            const welcomeMessage = `Welcome to AsyncAPI. Thanks a lot for creating your first pull request. Please check out our [contributors guide](https://github.com/asyncapi/community/blob/master/CONTRIBUTING.md) useful for opening a pull request.<br />Keep in mind there are also other channels you can use to interact with AsyncAPI community.`;
            const { owner, repo } = context.repo;
            const { number: issue_number } = context.issue;
            return github.issues.createComment({ owner, repo, issue_number, body: welcomeMessage });