# # A github action to check the reaction on pr and issues . 

# name: Check Reactions on Pr and Issue
# on:
#   issues:
#     types: [opened]
#   pull_request:
#     types: [opened, closed]
# jobs:
#   check-reactions:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Check Reactions
#         env:
#           GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
#         run: |
#           curl -H "Authorization: token $GITHUB_TOKEN" \
#             "https://api.github.com/repos/${{ github.repository }}/issues?state=all" \
#             | jq '.[] | {number: .number, title: .title, reactions: .reactions}'

## WORKFLOW WHIHC REPORT ISSUE OR PR WHICH HAVE MORE THAN 5 REACTION 


name: Measure Reactions on PR and Issue

on:
  issues:
    types: [opened, reopened, closed]
  pull_request: 
    types: [opened, closed]
  
jobs:
  measure-reactions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Measure reactions
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: python measure_reactions.py



