# # A github action to check the reaction on pr and issues . 

# name: Check Reactions on Pr and Issue
# on:
#   issues:
#     types: [opened]
#   pull_request:
#     types: [opened, closed]
# jobs:
#   check-reactions:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Check Reactions
#         env:
#           GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
#         run: |
#           curl -H "Authorization: token $GITHUB_TOKEN" \
#             "https://api.github.com/repos/${{ github.repository }}/issues?state=all" \
#             | jq '.[] | {number: .number, title: .title, reactions: .reactions}'

## WORKFLOW WHIHC REPORT ISSUE OR PR WHICH HAVE MORE THAN 5 REACTION 


name: Measure Emotions in PR and Issues

on:
  pull_request:
    types: [opened, edited, reopened]
  issues:
    types: [opened, edited, reopened]

jobs:
  measure-emotions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install requests
          pip install ibm-watson

      - name: Measure Emotions
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          IBM_API_KEY: ${{ secrets.IBM_API_KEY }}
          IBM_URL: ${{ secrets.IBM_URL }}
        run: python measure_reactions.py




