name: Update MAINTAINERS.yaml

on:
  pull_request:
    types: [opened]
    paths:
      - 'CODEOWNERS'

jobs:
  update-maintainers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install js-yaml
        run: npm install js-yaml@3.14.1

      - name: Get added codeowner
        id: get-line
        run: |
          ADDED_CODEOWNER=$(git diff origin/${{ github.base_ref }} -- CODEOWNERS | grep '^+' | grep -v '^\+\+ ' | awk -F'@' '{print $NF}' | awk '{print $1}')
          echo "::set-output name=added_codeowner::$ADDED_CODEOWNER"
          echo "Added Codeowner: $ADDED_CODEOWNER"

      - name: Get repository names
        id: get-repos
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          OWNER=$(echo "${{ github.repository }}" | cut -d'/' -f1)
          REPO=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          API_RESPONSE=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/repos/$OWNER/$REPO")
          REPO_NAMES=$(echo "$API_RESPONSE" | jq -r '.forks_url, .source.forks_url' | xargs -n1 basename | paste -sd "," -)
          echo "::set-output name=repo_names::$REPO_NAMES"
      
      - name: Update MAINTAINERS.yaml
        if: steps.get-line.outputs.added_codeowner != ''
        run: |
          echo "ADDED_CODEOWNER=${{ steps.get-line.outputs.added_codeowner }}" >> $GITHUB_ENV
          
          echo "Updating MAINTAINERS.yaml with added codeowner"
          echo "${{ steps.get-line.outputs.added_codeowner }}" > added_codeowner.txt
      
          echo 'const fs = require("fs");
          const yaml = require("js-yaml");
      
          const addedCodeowner = fs.readFileSync("added_codeowner.txt", "utf8").trim();
          const maintainers = yaml.safeLoad(fs.readFileSync("MAINTAINERS.yaml", "utf8"));
      
          const newMaintainer = maintainers.find(maintainer => maintainer.name === addedCodeowner);
      
          if (!newMaintainer) {
            const repoNames = process.env.REPO_NAMES.split(",");
            const newMaintainer = {
              name: "",
              github: addedCodeowner,
              slack: "",
              availableForHire: false,
              company: "",
              isTscMember: false,
              repos: repoNames
            };
      
            maintainers.push(newMaintainer);
      
            const updatedYaml = yaml.safeDump(maintainers);
            fs.writeFileSync("MAINTAINERS.yaml", updatedYaml);
            console.log("MAINTAINERS.yaml updated with new maintainer:", addedCodeowner);
          } else {
            console.log("Maintainer", addedCodeowner, "already exists in MAINTAINERS.yaml. Skipping update.");
          }
          ' | node -p
      
          cat MAINTAINERS.yaml
      
          rm added_codeowner.txt



      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add MAINTAINERS.yaml
          git commit -m "Update MAINTAINERS.yaml"
          git push origin HEAD:${{ github.base_ref }}
