name: Convert YAML to JSON Locally
on:
  push:
    branches:
      - "main"
    paths:
      - "MAINTAINERS.yaml"

jobs:
  convert:
    name: Convert YAML to JSON and print to console
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current repository
        uses: actions/checkout@v2

      - name: Install yaml2json
        run: |
          sudo apt-get install -y python3 python3-pip
          pip3 install yaml2json

      - name: Convert YAML to JSON
        run: |
          cat MAINTAINERS.yaml | yaml2json
