name: Update MAINTAINERS.yaml

on:
  pull_request:
    types: [synchronize]
    paths:
      - 'CODEOWNERS'

jobs:
  update_maintainers:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Check for new maintainers
        id: check-maintainers
        run: |
          NEW_MAINTAINER=$(git diff origin/${{ github.base_ref }} -- CODEOWNERS | grep '^+' | grep -v '^\+\+ ' | awk '{print $NF}' | tr -d '@')
          echo "NEW_MAINTAINER=$NEW_MAINTAINER" >> $GITHUB_ENV
          if [ -n "$NEW_MAINTAINER" ]; then
            echo "::set-output name=new-maintainer::true"
          fi
          
      - name: Update MAINTAINERS.yaml
        if: steps.check-maintainers.outputs.new-maintainer == 'true'
        run: |
          USERNAME=$NEW_MAINTAINER
          USER_DATA=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" "https://api.github.com/users/$USERNAME")
          REPO_NAME=$(git config --get remote.origin.url | rev | cut -d'/' -f1 | rev | cut -d'.' -f1)
          
          # Update MAINTAINERS.yaml (assuming you have Twitter handle already or it's manually updated)
          echo "$USERNAME:" >> MAINTAINERS.yaml
          echo "  name: $(echo $USER_DATA | jq -r '.name')" >> MAINTAINERS.yaml
          echo "  github: $USERNAME" >> MAINTAINERS.yaml
          echo "  repository: $REPO_NAME" >> MAINTAINERS.yaml
          
          # Commit changes
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add MAINTAINERS.yaml
          git commit -m "Update MAINTAINERS.yaml"
          git push
        env:
          PAT: ${{ secrets.PAT }}
