name: Update MAINTAINERS.yaml

on:
  pull_request:
    types: [opened]
    paths:
      - 'CODEOWNERS'

jobs:
  update-maintainers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed line
        id: get-line
        run: echo "::set-output name=line::$(git diff HEAD~1 HEAD -- CODEOWNERS | grep '^+' | grep -v '^\+\+ ')"

      - name: Parse GitHub username
        id: parse-username
        run: echo "::set-output name=username::$(echo \"${{ steps.get-line.outputs.line }}\" | awk '{print $NF}' | tr -d '@')"

      - name: Get committer name
        id: get-committer-name
        run: |
          COMMITTER_NAME=$(git log -1 --pretty=format:'%an')
          echo "COMMITTER_NAME=$COMMITTER_NAME" >> $GITHUB_ENV
          echo "Committer Name: $COMMITTER_NAME"

      - name: Update MAINTAINERS.yaml
        run: |
          echo "${{ steps.parse-username.outputs.username }}:" >> MAINTAINERS.yaml
          echo "  name: '${{ env.COMMITTER_NAME }}'" >> MAINTAINERS.yaml
          echo "  maintained_repository: 'testRepo'" >> MAINTAINERS.yaml
          cat MAINTAINERS.yaml
          echo "MAINTAINERS.yaml updated successfully"

      - name: Commit and push
        run: |
          git config user.name "${{ env.COMMITTER_NAME }}"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "update latest maintainers list"
          git push origin HEAD:main


