name: Convert YAML to JSON Locally
on:
  push:
    branches:
      - "main"
    paths:
      - "MAINTAINERS.yaml"

jobs:
  convert:
    name: Convert YAML to JSON and print to console
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current repository
        uses: actions/checkout@v2

      - name: Convert YAML to JSON
        run: |
          python -c 'import sys, yaml, json; json.dump(yaml.safe_load(sys.stdin), sys.stdout, indent=4)' < MAINTAINERS.yaml
