name: Update Maintainers

on:
  push:
    branches:
      - main
    paths:
      - 'CODEOWNERS'

jobs:
  update-maintainers:
    runs-on: ubuntu-latest
    
    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Get the changed line in CODEOWNERS (only works if one line has changed)
      - name: Get changed line
        id: get-line
        run: echo "::set-output name=line::$(git diff HEAD~1 HEAD -- CODEOWNERS | grep '^+' | grep -v '^\+\+ ')"
      
      # Parse GitHub username from the changed line
      - name: Parse GitHub username
        id: parse-username
        run: echo "::set-output name=username::$(echo "${{ steps.get-line.outputs.line }}" | awk '{print $NF}' | tr -d '@')"

      # Get the user's name from the GitHub API
      - name: Get user name
        id: get-user
        run: |
          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/users/${{ steps.parse-username.outputs.username }}")
          echo "::set-output name=name::$(echo $response | jq -r '.name')"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Update Maintainers.yaml file
      - name: Update Maintainers.yaml
        run: |
          echo "${{ steps.parse-username.outputs.username }}:" >> Maintainers.yaml
          echo "  name: \"${{ steps.get-user.outputs.name }}\"" >> Maintainers.yaml
          echo "  maintained_repository: \"<REPO_NAME>\"" >> Maintainers.yaml

      # Commit changes to the repository
      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Maintainers.yaml
          git commit -m "Update Maintainers.yaml"
          git push
