name: Update MAINTAINERS.yaml

on:
  pull_request:
    types: [opened]
    paths:
      - 'CODEOWNERS'

jobs:
  update-maintainers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install js-yaml
        run: npm install js-yaml@3.14.1

      - name: Get added codeowners
        id: codeowners
        run: |
          ADDED_CODEOWNERS=$(git diff origin/${{ github.base_ref }} -- CODEOWNERS | grep '^+' | grep -v '^\+\+ ' | awk '{print $NF}' | tr -d '@')
          REMOVED_CODEOWNERS=$(git diff origin/${{ github.base_ref }} -- CODEOWNERS | grep '^-[^-]' | grep -v '^\-\- ' | awk '{print $NF}' | tr -d '@')
          echo "ADDED_CODEOWNERS=$ADDED_CODEOWNERS" >> $GITHUB_ENV
          echo "REMOVED_CODEOWNERS=$REMOVED_CODEOWNERS" >> $GITHUB_ENV
          echo "Added Codeowners: $ADDED_CODEOWNERS"
          echo "Removed Codeowners: $REMOVED_CODEOWNERS"

      - name: Get repository name
        id: get-repo-name
        run: |
          REPO_NAME=$(basename ${{ github.repository }})
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "Repository Name: $REPO_NAME"

      - name: Update MAINTAINERS.yaml
        if: env.REPO_NAME && (env.ADDED_CODEOWNERS || env.REMOVED_CODEOWNERS)
        run: |
          echo "Updating MAINTAINERS.yaml with added and removed codeowners"

          echo "${{ steps.codeowners.outputs.ADDED_CODEOWNERS }}" > added_codeowners.txt
          echo "${{ steps.codeowners.outputs.REMOVED_CODEOWNERS }}" > removed_codeowners.txt

          ADDED_CODEOWNERS=$(cat added_codeowners.txt)
          REMOVED_CODEOWNERS=$(cat removed_codeowners.txt)

          echo "const fs = require('fs');
          const yaml = require('js-yaml');

          let maintainers = yaml.safeLoad(fs.readFileSync('MAINTAINERS.yaml', 'utf8'));

          // Remove codeowners from maintainers
          const updatedMaintainers = maintainers.filter((maintainer) => {
            return !REMOVED_CODEOWNERS.split('\n').includes(maintainer.github);
          });

          // Add codeowners to maintainers
          ADDED_CODEOWNERS.split('\n').forEach((addedCodeowner) => {
            const newMaintainer = updatedMaintainers.find((maintainer) => maintainer.github === addedCodeowner);
            if (!newMaintainer) {
              const repoName = process.env.REPO_NAME;
              const newMaintainer = {
                name: '',
                github: addedCodeowner,
                slack: '',
                availableForHire: false,
                company: '',
                isTscMember: false,
                repos: [repoName]
              };
              updatedMaintainers.push(newMaintainer);
            }
          });

          const updatedYaml = yaml.safeDump(updatedMaintainers);
          fs.writeFileSync('MAINTAINERS.yaml', updatedYaml);
          console.log('MAINTAINERS.yaml updated.');

          console.log(updatedYaml);"
          cat MAINTAINERS.yaml

          rm added_codeowners.txt
          rm removed_codeowners.txt
