name: Update MAINTAINERS.yaml

on:
  pull_request:
    types: [opened]
    paths:
      - 'CODEOWNERS'

jobs:
  update-maintainers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get added line
        id: get-line
        run: |
          ADDED_LINE=$(git diff origin/${{ github.base_ref }} -- CODEOWNERS | grep '^+' | grep -v '^\+\+ ')
          echo "::set-output name=added_line::$ADDED_LINE"
          echo "Added Line: $ADDED_LINE"

      - name: Update MAINTAINERS.yaml with JavaScript
        if: steps.get-line.outputs.added_line != ''
        run: |
          const fs = require('fs');
          const yaml = require('js-yaml');

          // Read MAINTAINERS.yaml
          const file = fs.readFileSync('MAINTAINERS.yaml', 'utf8');
          const data = yaml.load(file);

          // Parse added line
          const addedLine = '${{ steps.get-line.outputs.added_line }}';
          const name = addedLine.split(':')[1].trim();
          const github = addedLine.split(':')[2].trim();
          const slack = addedLine.split(':')[3].trim();
          const availableForHire = addedLine.split(':')[4].trim();
          const company = addedLine.split(':')[5].trim();
          const isTscMember = addedLine.split(':')[6].trim();
          const repos = addedLine.split(':')[7].trim().split(', ');

          console.log(`Name: ${name}`);
          console.log(`GitHub: ${github}`);
          console.log(`Slack: ${slack}`);
          console.log(`Available for Hire: ${availableForHire}`);
          console.log(`Company: ${company}`);
          console.log(`Is TSC Member: ${isTscMember}`);
          console.log(`Repos: ${repos}`);

          // Create new maintainer object
          const newMaintainer = {
            name: name,
            github: github,
            slack: slack,
            availableForHire: availableForHire === 'true',
            company: company,
            isTscMember: isTscMember === 'true',
            repos: repos
          };

          // Add new maintainer to the data
          data.push(newMaintainer);

          // Write back to MAINTAINERS.yaml
          fs.writeFileSync('MAINTAINERS.yaml', yaml.dump(data), 'utf8');
          console.log('MAINTAINERS.yaml updated successfully');

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add MAINTAINERS.yaml
          git commit -m "Update MAINTAINERS.yaml"
          git push origin HEAD:${{ github.base_ref }}
