name: Update MAINTAINERS.yaml

on:
  pull_request:
    types: [opened]
    paths:
      - 'CODEOWNERS'

jobs:
  update-maintainers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get added line
        id: get-line
        run: |
          ADDED_CODEOWNER=$(git diff origin/${{ github.base_ref }} -- CODEOWNERS | grep '^+' | grep -v '^\+\+ ')
          echo "::set-output name=added_codeowner::$ADDED_CODEOWNER"
          echo "Added Codeowner: $ADDED_CODEOWNER"

      - name: Update MAINTAINERS.yaml
        if: steps.get-line.outputs.added_codeowner != ''
        run: |
          echo "${{ steps.get-line.outputs.added_codeowner }}" > added_codeowner.txt
          echo 'const fs = require("fs");
          const yaml = require("js-yaml");

          const addedCodeowner = fs.readFileSync("added_codeowner.txt", "utf8").trim();
          const maintainers = yaml.safeLoad(fs.readFileSync("MAINTAINERS.yaml", "utf8"));

          const newMaintainer = {
            name: "",
            github: "",
            slack: "",
            availableForHire: false,
            company: "",
            isTscMember: false,
            repos: []
          };

          // Update newMaintainer object properties based on addedCodeowner content

          maintainers.push(newMaintainer);

          const updatedYaml = yaml.safeDump(maintainers);
          fs.writeFileSync("MAINTAINERS.yaml", updatedYaml);
          ' | node

          rm added_codeowner.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add MAINTAINERS.yaml
          git commit -m "Update MAINTAINERS.yaml"
          git push origin HEAD:${{ github.base_ref }}
