name: Update MAINTAINERS.yaml

on:
  push:
    branches:
      - main
    paths:
      - 'CODEOWNERS'

jobs:
  update-maintainers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed line
        id: get-line
        run: echo "::set-output name=line::$(git diff HEAD~1 HEAD -- CODEOWNERS | grep '^+' | grep -v '^\+\+ ')"

      - name: Parse GitHub username
        id: parse-username
        run: echo "::set-output name=username::$(echo \"${{ steps.get-line.outputs.line }}\" | awk '{print $NF}' | tr -d '@')"

      - name: Get committer name
        id: get-committer-name
        run: |
          COMMITTER_NAME=$(git log -1 --pretty=format:'%an')
          echo "COMMITTER_NAME=$COMMITTER_NAME" >> $GITHUB_ENV
          echo "Committer Name: $COMMITTER_NAME"

      - name: Update MAINTAINERS.yaml
        run: |
          echo "${{ steps.parse-username.outputs.username }}:" >> MAINTAINERS.yaml
          echo "  name: '${{ env.COMMITTER_NAME }}'" >> MAINTAINERS.yaml
          echo "  maintained_repository: 'testRepo'" >> MAINTAINERS.yaml
          cat MAINTAINERS.yaml
          echo "MAINTAINERS.yaml updated successfully"

      - name: Commit changes
        run: |
          git config --global user.name "${{ env.COMMITTER_NAME }}"
          git config --global user.email "onlinericha19@gmail.com"
          git remote add auth_origin https://${{ github.actor }}:${{ secrets.BOT_TOKEN }}@github.com/${{ github.repository }}
          git remote -v
          git push auth_origin HEAD:main
          echo "Changes committed successfully"
