name: Update MAINTAINERS.yaml

on:
  push:
    branches:
      - main
    paths:
      - 'CODEOWNERS'

jobs:
  update-maintainers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed line
        id: get-line
        run: echo "::set-output name=line::$(git diff HEAD~1 HEAD -- CODEOWNERS | grep '^+' | grep -v '^\+\+ ')"

      - name: Parse GitHub username
        id: parse-username
        run: echo "::set-output name=username::$(echo \"${{ steps.get-line.outputs.line }}\" | awk '{print $NF}' | tr -d '@')"

      - name: Get committer name
        id: get-committer-name
        run: |
          committer_name=$(git log -1 --pretty=format:'%an')
          echo "::set-output name=name::${committer_name}"
          echo "Committer Name: $committer_name"

      - name: Update MAINTAINERS.yaml
        run: |
          echo "${{ steps.parse-username.outputs.username }}:" >> MAINTAINERS.yaml
          echo "  name: \"${{ steps.get-committer-name.outputs.name }}\"" >> MAINTAINERS.yaml
          echo "  maintained_repository: \"testRepo\"" >> MAINTAINERS.yaml

      - name: Commit changes
        env:
          GIT_COMMITTER_NAME: ${{ steps.get-committer-name.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
        run: |
          git config --global user.name "$GIT_COMMITTER_NAME"
          git config --global user.email "$GIT_COMMITTER_EMAIL"
          git remote add auth_origin https://${{ github.actor }}:${{ secrets.BOT_TOKEN }}@github.com/${{ github.repository }}
          git remote -v
          git push auth_origin HEAD:main
