name: Validate Maintainers

on:
  pull_request:
    paths:
      - 'Maintainers.yaml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Check for changes made by a bot
        run: |
          if [ "$(git log -1 --pretty=format:'%an' Maintainers.yaml)" != "github-actions[bot]" ]; then
            echo "Error: Changes to Maintainers.yaml file must be made by the bot."
            exit 1
          else
            echo "Changes to Maintainers.yaml file were made by the bot, continuing with the workflow."
          fi

      - name: Close pull request if changes were made by a human
        uses: actions/github-script@v5
        if: ${{ failure() }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pull } = await github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              state: 'closed',
              body: `Hi @${{ github.event.pull_request.user.login }}, changes to the Maintainers.yaml file can only be made by the bot. Therefore, this pull request has been closed. Please make sure that any changes to the Maintainers.yaml file are made by the bot and not by a human.`
            });
            console.log(`Closed pull request: ${pull.html_url}`);


## Added asyncapi bot account 

# name: Validate Maintainers
# on:
#   pull_request:
#     paths:
#       - 'Maintainers.yaml'

# jobs:
#   validate:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Check for changes made by the asyncapi-bot
#         run: |
#           if [ "$(git log -1 --pretty=format:'%an' Maintainers.yaml)" != "asyncapi-bot" ]; then
#             echo "Error: Changes to Maintainers.yaml file must be made by the asyncapi-bot."
#             exit 1
#           fi