# name: Verify Maintainers Changes

# on:
#   pull_request:
#     paths:
#       - "Maintainers.yaml"

# jobs:
#   verify-changes:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Fetch all branches
#         run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: "14"

#       - name: Install dependencies
#         run: npm install yaml

#       - name: Verify changes
#         run: node .github/workflows/verify-maintainers-changes.js ${{ github.event.pull_request.user.login }}

name: Verify Maintainers Changes

on:
  pull_request:
    paths:
      - "Maintainers.yaml"

jobs:
  verify-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install yaml

      - name: Verify changes
        id: verify
        run: node .github/workflows/verify-maintainers-changes.js ${{ github.event.pull_request.user.login }}
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Close PR and Comment
        if: steps.verify.outputs.isCriticalChange == 'true'
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.BOT_TOKEN}}
          script: |
            github.rest.pulls.update({
              owner: '14Richa',
              repo: 'testRepo',
              pull_number: ${{ github.event.pull_request.number }},
              state: 'closed'
            });

            github.rest.issues.createComment({
              owner: '14Richa',
              repo: 'testRepo',
              issue_number: ${{ github.event.pull_request.number }},
              body: 'Critical changes have been made. This PR needs to be reviewed.'
            });
