name: Verify Maintainers Changes

on:
  pull_request:
    types: [synchronize, opened]
    paths:
      - "Maintainers.yaml"

jobs:
  verify-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: main-branch

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          path: pr-branch

      - name: Install Dependencies
        run: npm install yaml

      - name: Verify changes in Maintainers.yaml
        id: verify-changes
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            const yaml = require("yaml");
            const fs = require("fs");

            const mainFile = yaml.parse(fs.readFileSync("./main-branch/Maintainers.yaml", "utf8"));
            const prFile = yaml.parse(fs.readFileSync("./pr-branch/Maintainers.yaml", "utf8"));

            const beforeMaintainers = new Map(mainFile.map((maintainer) => [maintainer.name, maintainer.github]));
            let isCriticalChangeDetected = false;
            let criticalChangeMessage = '';

            for (const maintainer of prFile) {
              if (!beforeMaintainers.has(maintainer.name)) {
                criticalChangeMessage = `Critical changes have been made to Maintainers.yaml by ${maintainer.name}. A new maintainer object has been added. Please review.`;
                isCriticalChangeDetected = true;
                break;
              } else if (beforeMaintainers.get(maintainer.name) !== maintainer.github) {
                criticalChangeMessage = `Critical changes have been made to Maintainers.yaml. GitHub username has been modified for ${maintainer.name}. Please review.`;
                isCriticalChangeDetected = true;
                break;
              }
            }

            // If critical change is detected, create a comment on the PR and close it.
            if (isCriticalChangeDetected) {
                const owner = "${{ github.repository_owner }}";
                const repo = "${{ github.event.repository.name }}";
                const issue_number = "${{ github.event.pull_request.number }}";
                
                github.rest.issues.createComment({
                    owner,
                    repo,
                    issue_number,
                    body: criticalChangeMessage
                });

                // Close the PR
                github.rest.pulls.update({
                    owner,
                    repo,
                    pull_number: issue_number,
                    state: 'closed'
                });
            }
