name: Verify Maintainers Changes

on:
  pull_request:
    paths:
      - "Maintainers.yaml"

jobs:
  verify-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: repo-main

      - name: Checkout one commit before last one
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          ref: main
          path: repo-pr
      - run: cd repo-pr && git checkout HEAD^

      - name: Verify changes
        id: verify
        uses: actions/github-script@v5
        with:
          script: |
            const verifyMaintainersChanges = require('./verify-maintainers-changes.js');
            const prAuthor = '${{ github.event.pull_request.user.login }}';
            const mainPath = 'repo-main/MAINTAINERS.yaml';
            const prPath = 'repo-pr/MAINTAINERS.yaml';
            return verifyMaintainersChanges(prAuthor, mainPath, prPath);
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Close PR and Comment
        if: steps.verify.outputs.result == 'true'
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.BOT_TOKEN}}
          script: |
            github.rest.pulls.update({
              owner: '14Richa',
              repo: 'testRepo',
              pull_number: ${{ github.event.pull_request.number }},
              state: 'closed'
            });
            github.rest.issues.createComment({
              owner: '14Richa',
              repo: 'testRepo',
              issue_number: ${{ github.event.pull_request.number }},
              body: 'Critical changes have been made. This PR needs to be reviewed.'
            });
