name: Verify Maintainers Changes

on:
  pull_request:
    types: [synchronize, opened]
    paths:
      - "Maintainers.yaml"

jobs:
  verify-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: main-branch

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          path: pr-branch

      - name: Install Dependencies
        run: npm install yaml

      - name: Verify changes in Maintainers.yaml
        id: verify-changes
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            const yaml = require("yaml");
            const fs = require("fs");

            const mainFile = yaml.parse(fs.readFileSync("./main-branch/Maintainers.yaml", "utf8"));
            const prFile = yaml.parse(fs.readFileSync("./pr-branch/Maintainers.yaml", "utf8"));

            const beforeMaintainers = new Map(mainFile.map((maintainer) => [maintainer.name, maintainer.github]));
            let isCriticalChangeDetected = false;

            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');

            for (const maintainer of prFile) {
              const previousGithub = beforeMaintainers.get(maintainer.name);
              if (!beforeMaintainers.has(maintainer.name) || (previousGithub && previousGithub !== maintainer.github)) {
                core.error(`Critical changes have been made to Maintainers.yaml by ${maintainer.name}. GitHub key has been modified or new maintainer has been added. Please review.`);
                isCriticalChangeDetected = true;
                break;
              }
            }

            // If critical change is detected, create a comment on the PR and close it.
            if (isCriticalChangeDetected) {
                const pull_number = github.event.number;
                github.rest.issues.createComment({ owner, repo, issue_number: pull_number, body: 'Critical changes detected in Maintainers.yaml. GitHub key has been modified or new maintainer has been added. Please review.' });

                // Close the PR
                github.rest.pulls.update({
                    owner,
                    repo,
                    pull_number,
                    state: 'closed'
                });
            }
