name: Verify Maintainers Changes

on:
  pull_request:
    paths:
      - "Maintainers.yaml"

jobs:
  verify-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Verify changes
        run: node .github/workflows/verify_changes.js ${{ github.event.pull_request.user.login }}
